# DUT.Models.Blogpost.dcm.yml

DUT\Models\Blogpost:

  # Informations
  table: pwsb_blogpost # => MySQL Table Name
  type: entity
  oneToMany:
    comments:
      targetEntity: Comment
      mappedBy: blogpost

  # ID(s) fields
  id:
    id:
      type: integer
      generator:
        strategy: auto

  # Other fields
  fields:
    date:
      type: string
      column: date
      nullable: false
    title:
      type: string
      column: title
      nullable: false
    content:
      type: string
      column: content
      nullable: false
    image:
      type: string
      column: image
      nullable: true